# Generated by Django 5.2.4 on 2025-10-19 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houndexpress', '0002_alter_estatus_id_alter_guia_id_alter_usuario_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatus',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='estatus',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Estatus', 'verbose_name_plural': 'Estatus'},
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
