# Generated by Django 5.2.4 on 2025-10-20 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houndexpress', '0003_alter_estatus_updatedby_alter_estatus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='estatus',
            constraint=models.UniqueConstraint(fields=('guide', 'status'), name='unique_guide_status'),
        ),
    ]
