# Generated by Django 5.2.4 on 2025-11-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houndexpress', '0004_estatus_unique_guide_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='estatus',
            name='unique_guide_status',
        ),
        migrations.RenameField(
            model_name='estatus',
            old_name='guide',
            new_name='guide_data',
        ),
        migrations.RenameField(
            model_name='estatus',
            old_name='status',
            new_name='guide_status',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='currentStatus',
            new_name='current_status',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='destination',
            new_name='guide_destination',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='trackingNumber',
            new_name='guide_number',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='origin',
            new_name='guide_origin',
        ),
        migrations.RemoveField(
            model_name='estatus',
            name='updatedBy',
        ),
        migrations.AddField(
            model_name='guia',
            name='guide_recipient',
            field=models.CharField(default='Usuarios destino', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='estatus',
            constraint=models.UniqueConstraint(fields=('guide_data', 'guide_status'), name='unique_guide_status'),
        ),
    ]
