# Generated by Django 5.2.4 on 2025-11-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houndexpress', '0005_remove_estatus_unique_guide_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guia',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='guia',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
